#!/bin/sh
pgm="${0##*/}"          # Program basename
progdir="${0%/*}"       # Program directory
: ${REALPATH_CMD=$( which realpath )}
: ${SQLITE3_CMD=$( which sqlite3 )}
: ${RM_CMD=$( which rm )}
: ${MKDIR_CMD=$( which mkdir )}
: ${FORM_PATH="/opt/forms"}
: ${distdir="/usr/local/cbsd"}

MY_PATH="$( ${REALPATH_CMD} ${progdir} )"
HELPER="timezone"

# MAIN
if [ -z "${workdir}" ]; then
	[ -z "${cbsd_workdir}" ] && . /etc/rc.conf
	[ -z "${cbsd_workdir}" ] && exit 0
	workdir="${cbsd_workdir}"
fi

set -e
. ${distdir}/cbsd.conf
. ${subrdir}/tools.subr
. ${subr}
set +e

FORM_PATH="${workdir}/formfile"

[ ! -d "${FORM_PATH}" ] && err 1 "No such ${FORM_PATH}"
[ -f "${FORM_PATH}/${HELPER}.sqlite" ] && ${RM_CMD} -f "${FORM_PATH}/${HELPER}.sqlite"

/usr/local/bin/cbsd ${miscdir}/updatesql ${FORM_PATH}/${HELPER}.sqlite ${distsharedir}/forms.schema forms
/usr/local/bin/cbsd ${miscdir}/updatesql ${FORM_PATH}/${HELPER}.sqlite ${distsharedir}/forms.schema additional_cfg
/usr/local/bin/cbsd ${miscdir}/updatesql ${FORM_PATH}/${HELPER}.sqlite ${distsharedir}/forms_system.schema system

${SQLITE3_CMD} ${FORM_PATH}/${HELPER}.sqlite << EOF
BEGIN TRANSACTION;
INSERT INTO forms ( mytable,group_id,order_id,param,desc,def,cur,new,mandatory,attr,type,link,groupname ) VALUES ( 'forms', 1,1,'timezone','timezone: default is 'UTC'','UTC','','',1, 'maxlen=60', 'inputbox', 'timezone_autocomplete', '' );
COMMIT;
EOF


# autocomplete
/usr/local/bin/cbsd ${miscdir}/updatesql ${FORM_PATH}/${HELPER}.sqlite ${distsharedir}/forms_yesno.schema timezone_autocomplete

# Autocomplete
# see complete.sh script
${SQLITE3_CMD} ${FORM_PATH}/${HELPER}.sqlite << EOF
BEGIN TRANSACTION;
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Abidjan', 1 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Accra', 2 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Addis_Ababa', 3 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Algiers', 4 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Asmara', 5 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Asmera', 6 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Bamako', 7 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Bangui', 8 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Banjul', 9 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Bissau', 10 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Blantyre', 11 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Brazzaville', 12 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Bujumbura', 13 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Cairo', 14 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Casablanca', 15 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Ceuta', 16 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Conakry', 17 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Dakar', 18 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Dar_es_Salaam', 19 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Djibouti', 20 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Douala', 21 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/El_Aaiun', 22 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Freetown', 23 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Gaborone', 24 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Harare', 25 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Johannesburg', 26 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Juba', 27 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Kampala', 28 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Khartoum', 29 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Kigali', 30 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Kinshasa', 31 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Lagos', 32 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Libreville', 33 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Lome', 34 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Luanda', 35 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Lubumbashi', 36 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Lusaka', 37 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Malabo', 38 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Maputo', 39 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Maseru', 40 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Mbabane', 41 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Mogadishu', 42 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Monrovia', 43 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Nairobi', 44 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Ndjamena', 45 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Niamey', 46 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Nouakchott', 47 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Ouagadougou', 48 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Porto-Novo', 49 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Sao_Tome', 50 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Timbuktu', 51 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Tripoli', 52 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Tunis', 53 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Africa/Windhoek', 54 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Adak', 55 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Anchorage', 56 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Anguilla', 57 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Antigua', 58 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Araguaina', 59 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/Buenos_Aires', 60 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/Catamarca', 61 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/ComodRivadavia', 62 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/Cordoba', 63 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/Jujuy', 64 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/La_Rioja', 65 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/Mendoza', 66 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/Rio_Gallegos', 67 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/Salta', 68 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/San_Juan', 69 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/San_Luis', 70 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/Tucuman', 71 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Argentina/Ushuaia', 72 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Aruba', 73 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Asuncion', 74 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Atikokan', 75 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Atka', 76 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Bahia', 77 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Bahia_Banderas', 78 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Barbados', 79 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Belem', 80 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Belize', 81 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Blanc-Sablon', 82 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Boa_Vista', 83 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Bogota', 84 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Boise', 85 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Buenos_Aires', 86 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Cambridge_Bay', 87 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Campo_Grande', 88 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Cancun', 89 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Caracas', 90 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Catamarca', 91 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Cayenne', 92 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Cayman', 93 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Chicago', 94 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Chihuahua', 95 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Ciudad_Juarez', 96 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Coral_Harbour', 97 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Cordoba', 98 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Costa_Rica', 99 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Creston', 100 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Cuiaba', 101 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Curacao', 102 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Danmarkshavn', 103 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Dawson', 104 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Dawson_Creek', 105 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Denver', 106 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Detroit', 107 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Dominica', 108 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Edmonton', 109 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Eirunepe', 110 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/El_Salvador', 111 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Ensenada', 112 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Fort_Nelson', 113 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Fort_Wayne', 114 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Fortaleza', 115 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Glace_Bay', 116 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Godthab', 117 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Goose_Bay', 118 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Grand_Turk', 119 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Grenada', 120 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Guadeloupe', 121 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Guatemala', 122 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Guayaquil', 123 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Guyana', 124 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Halifax', 125 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Havana', 126 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Hermosillo', 127 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Indiana/Indianapolis', 128 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Indiana/Knox', 129 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Indiana/Marengo', 130 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Indiana/Petersburg', 131 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Indiana/Tell_City', 132 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Indiana/Vevay', 133 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Indiana/Vincennes', 134 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Indiana/Winamac', 135 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Indianapolis', 136 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Inuvik', 137 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Iqaluit', 138 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Jamaica', 139 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Jujuy', 140 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Juneau', 141 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Kentucky/Louisville', 142 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Kentucky/Monticello', 143 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Knox_IN', 144 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Kralendijk', 145 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/La_Paz', 146 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Lima', 147 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Los_Angeles', 148 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Louisville', 149 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Lower_Princes', 150 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Maceio', 151 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Managua', 152 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Manaus', 153 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Marigot', 154 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Martinique', 155 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Matamoros', 156 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Mazatlan', 157 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Mendoza', 158 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Menominee', 159 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Merida', 160 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Metlakatla', 161 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Mexico_City', 162 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Miquelon', 163 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Moncton', 164 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Monterrey', 165 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Montevideo', 166 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Montreal', 167 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Montserrat', 168 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Nassau', 169 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/New_York', 170 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Nipigon', 171 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Nome', 172 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Noronha', 173 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/North_Dakota/Beulah', 174 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/North_Dakota/Center', 175 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/North_Dakota/New_Salem', 176 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Nuuk', 177 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Ojinaga', 178 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Panama', 179 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Pangnirtung', 180 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Paramaribo', 181 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Phoenix', 182 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Port-au-Prince', 183 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Port_of_Spain', 184 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Porto_Acre', 185 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Porto_Velho', 186 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Puerto_Rico', 187 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Punta_Arenas', 188 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Rainy_River', 189 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Rankin_Inlet', 190 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Recife', 191 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Regina', 192 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Resolute', 193 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Rio_Branco', 194 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Rosario', 195 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Santa_Isabel', 196 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Santarem', 197 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Santiago', 198 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Santo_Domingo', 199 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Sao_Paulo', 200 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Scoresbysund', 201 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Shiprock', 202 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Sitka', 203 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/St_Barthelemy', 204 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/St_Johns', 205 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/St_Kitts', 206 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/St_Lucia', 207 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/St_Thomas', 208 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/St_Vincent', 209 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Swift_Current', 210 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Tegucigalpa', 211 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Thule', 212 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Thunder_Bay', 213 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Tijuana', 214 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Toronto', 215 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Tortola', 216 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Vancouver', 217 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Virgin', 218 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Whitehorse', 219 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Winnipeg', 220 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Yakutat', 221 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'America/Yellowknife', 222 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/Casey', 223 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/Davis', 224 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/DumontDUrville', 225 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/Macquarie', 226 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/Mawson', 227 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/McMurdo', 228 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/Palmer', 229 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/Rothera', 230 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/South_Pole', 231 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/Syowa', 232 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/Troll', 233 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Antarctica/Vostok', 234 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Arctic/Longyearbyen', 235 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Aden', 236 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Almaty', 237 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Amman', 238 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Anadyr', 239 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Aqtau', 240 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Aqtobe', 241 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Ashgabat', 242 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Ashkhabad', 243 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Atyrau', 244 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Baghdad', 245 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Bahrain', 246 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Baku', 247 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Bangkok', 248 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Barnaul', 249 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Beirut', 250 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Bishkek', 251 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Brunei', 252 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Calcutta', 253 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Chita', 254 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Choibalsan', 255 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Chongqing', 256 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Chungking', 257 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Colombo', 258 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Dacca', 259 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Damascus', 260 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Dhaka', 261 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Dili', 262 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Dubai', 263 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Dushanbe', 264 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Famagusta', 265 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Gaza', 266 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Harbin', 267 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Hebron', 268 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Ho_Chi_Minh', 269 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Hong_Kong', 270 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Hovd', 271 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Irkutsk', 272 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Istanbul', 273 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Jakarta', 274 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Jayapura', 275 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Jerusalem', 276 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Kabul', 277 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Kamchatka', 278 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Karachi', 279 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Kashgar', 280 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Kathmandu', 281 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Katmandu', 282 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Khandyga', 283 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Kolkata', 284 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Krasnoyarsk', 285 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Kuala_Lumpur', 286 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Kuching', 287 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Kuwait', 288 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Macao', 289 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Macau', 290 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Magadan', 291 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Makassar', 292 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Manila', 293 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Muscat', 294 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Nicosia', 295 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Novokuznetsk', 296 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Novosibirsk', 297 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Omsk', 298 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Oral', 299 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Phnom_Penh', 300 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Pontianak', 301 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Pyongyang', 302 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Qatar', 303 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Qostanay', 304 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Qyzylorda', 305 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Rangoon', 306 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Riyadh', 307 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Saigon', 308 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Sakhalin', 309 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Samarkand', 310 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Seoul', 311 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Shanghai', 312 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Singapore', 313 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Srednekolymsk', 314 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Taipei', 315 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Tashkent', 316 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Tbilisi', 317 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Tehran', 318 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Tel_Aviv', 319 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Thimbu', 320 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Thimphu', 321 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Tokyo', 322 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Tomsk', 323 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Ujung_Pandang', 324 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Ulaanbaatar', 325 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Ulan_Bator', 326 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Urumqi', 327 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Ust-Nera', 328 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Vientiane', 329 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Vladivostok', 330 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Yakutsk', 331 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Yangon', 332 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Yekaterinburg', 333 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Asia/Yerevan', 334 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Azores', 335 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Bermuda', 336 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Canary', 337 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Cape_Verde', 338 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Faeroe', 339 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Faroe', 340 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Jan_Mayen', 341 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Madeira', 342 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Reykjavik', 343 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/South_Georgia', 344 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/St_Helena', 345 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Atlantic/Stanley', 346 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/ACT', 347 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Adelaide', 348 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Brisbane', 349 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Broken_Hill', 350 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Canberra', 351 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Currie', 352 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Darwin', 353 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Eucla', 354 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Hobart', 355 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/LHI', 356 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Lindeman', 357 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Lord_Howe', 358 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Melbourne', 359 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/NSW', 360 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/North', 361 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Perth', 362 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Queensland', 363 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/South', 364 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Sydney', 365 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Tasmania', 366 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Victoria', 367 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/West', 368 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Australia/Yancowinna', 369 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Brazil/Acre', 370 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Brazil/DeNoronha', 371 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Brazil/East', 372 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Brazil/West', 373 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'CET', 374 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'CST6CDT', 375 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Canada/Atlantic', 376 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Canada/Central', 377 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Canada/Eastern', 378 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Canada/Mountain', 379 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Canada/Newfoundland', 380 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Canada/Pacific', 381 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Canada/Saskatchewan', 382 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Canada/Yukon', 383 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Chile/Continental', 384 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Chile/EasterIsland', 385 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Cuba', 386 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'EET', 387 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'EST', 388 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'EST5EDT', 389 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Egypt', 390 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Eire', 391 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT', 392 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+0', 393 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+1', 394 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+10', 395 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+11', 396 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+12', 397 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+2', 398 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+3', 399 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+4', 400 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+5', 401 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+6', 402 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+7', 403 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+8', 404 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT+9', 405 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-0', 406 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-1', 407 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-10', 408 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-11', 409 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-12', 410 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-13', 411 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-14', 412 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-2', 413 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-3', 414 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-4', 415 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-5', 416 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-6', 417 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-7', 418 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-8', 419 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT-9', 420 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/GMT0', 421 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/Greenwich', 422 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/UCT', 423 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/UTC', 424 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/Universal', 425 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Etc/Zulu', 426 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Amsterdam', 427 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Andorra', 428 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Astrakhan', 429 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Athens', 430 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Belfast', 431 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Belgrade', 432 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Berlin', 433 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Bratislava', 434 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Brussels', 435 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Bucharest', 436 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Budapest', 437 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Busingen', 438 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Chisinau', 439 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Copenhagen', 440 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Dublin', 441 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Gibraltar', 442 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Guernsey', 443 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Helsinki', 444 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Isle_of_Man', 445 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Istanbul', 446 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Jersey', 447 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Kaliningrad', 448 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Kiev', 449 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Kirov', 450 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Kyiv', 451 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Lisbon', 452 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Ljubljana', 453 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/London', 454 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Luxembourg', 455 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Madrid', 456 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Malta', 457 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Mariehamn', 458 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Minsk', 459 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Monaco', 460 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Moscow', 461 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Nicosia', 462 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Oslo', 463 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Paris', 464 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Podgorica', 465 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Prague', 466 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Riga', 467 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Rome', 468 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Samara', 469 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/San_Marino', 470 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Sarajevo', 471 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Saratov', 472 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Simferopol', 473 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Skopje', 474 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Sofia', 475 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Stockholm', 476 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Tallinn', 477 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Tirane', 478 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Tiraspol', 479 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Ulyanovsk', 480 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Uzhgorod', 481 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Vaduz', 482 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Vatican', 483 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Vienna', 484 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Vilnius', 485 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Volgograd', 486 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Warsaw', 487 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Zagreb', 488 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Zaporozhye', 489 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Europe/Zurich', 490 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Factory', 491 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'GB', 492 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'GB-Eire', 493 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'GMT', 494 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'GMT+0', 495 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'GMT-0', 496 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'GMT0', 497 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Greenwich', 498 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'HST', 499 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Hongkong', 500 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Iceland', 501 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Antananarivo', 502 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Chagos', 503 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Christmas', 504 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Cocos', 505 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Comoro', 506 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Kerguelen', 507 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Mahe', 508 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Maldives', 509 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Mauritius', 510 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Mayotte', 511 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Indian/Reunion', 512 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Iran', 513 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Israel', 514 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Jamaica', 515 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Japan', 516 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Kwajalein', 517 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Libya', 518 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'MET', 519 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'MST', 520 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'MST7MDT', 521 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Mexico/BajaNorte', 522 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Mexico/BajaSur', 523 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Mexico/General', 524 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'NZ', 525 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'NZ-CHAT', 526 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Navajo', 527 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'PRC', 528 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'PST8PDT', 529 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Apia', 530 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Auckland', 531 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Bougainville', 532 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Chatham', 533 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Chuuk', 534 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Easter', 535 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Efate', 536 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Enderbury', 537 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Fakaofo', 538 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Fiji', 539 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Funafuti', 540 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Galapagos', 541 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Gambier', 542 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Guadalcanal', 543 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Guam', 544 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Honolulu', 545 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Johnston', 546 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Kanton', 547 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Kiritimati', 548 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Kosrae', 549 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Kwajalein', 550 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Majuro', 551 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Marquesas', 552 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Midway', 553 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Nauru', 554 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Niue', 555 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Norfolk', 556 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Noumea', 557 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Pago_Pago', 558 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Palau', 559 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Pitcairn', 560 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Pohnpei', 561 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Ponape', 562 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Port_Moresby', 563 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Rarotonga', 564 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Saipan', 565 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Samoa', 566 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Tahiti', 567 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Tarawa', 568 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Tongatapu', 569 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Truk', 570 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Wake', 571 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Wallis', 572 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Pacific/Yap', 573 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Poland', 574 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Portugal', 575 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'ROC', 576 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'ROK', 577 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Singapore', 578 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Turkey', 579 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'UCT', 580 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Alaska', 581 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Aleutian', 582 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Arizona', 583 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Central', 584 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/East-Indiana', 585 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Eastern', 586 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Hawaii', 587 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Indiana-Starke', 588 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Michigan', 589 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Mountain', 590 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Pacific', 591 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'US/Samoa', 592 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'UTC', 593 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Universal', 594 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'W-SU', 595 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'WET', 596 );
INSERT INTO timezone_autocomplete ( text, order_id ) VALUES ( 'Zulu', 597 );
COMMIT;
EOF

${SQLITE3_CMD} ${FORM_PATH}/${HELPER}.sqlite << EOF
BEGIN TRANSACTION;
INSERT INTO system ( helpername, version, packages, have_restart ) VALUES ( 'timezone', '201607', '', '' );
COMMIT;
EOF


# long description
${SQLITE3_CMD} ${FORM_PATH}/${HELPER}.sqlite << EOF
BEGIN TRANSACTION;
UPDATE system SET longdesc='\
Manage timezone \
';
COMMIT;
EOF
